/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainInterface.PurchaseRole;

import Model.DB4OUtil.DB4OUtil;
import Model.EcoSys;
import Model.Enterprise.Enterprise;
import Model.Enterprise.DistributorEnterprise;
import Model.Network.Network;
import Model.Organization.DistributorOrg;
import Model.Organization.Organization;
import Model.Organization.OrderInventory;
import Model.Organization.OrderOrganization;
import Model.Organization.VaccineCount;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.WorkReq;
import Model.WorkQueue.requestVaccine;
import Model.WorkQueue.vaccineCount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import MainInterface.ManufactureRole.VaccineJPanel;

/**
 *
 * @author Sameer Nimse
 */
public class PurchaseAreaJPanel extends javax.swing.JPanel {
        
    private JPanel userProcessContainer;
    private OrderOrganization organization;
    private Enterprise enterprise;
    private EcoSys system;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public int currEP;
    public int currentCount;
    /**
     * Creates new form DistributionWorkAreaJPanel
     */
    public PurchaseAreaJPanel(JPanel userProcessContainer, UserAccount account, OrderOrganization organization, Enterprise enterprise, EcoSys system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = account;
        currEP = ((DistributorEnterprise) enterprise).getVaccineCount();
        currentCount = 0;
        lblValue.setText(account.getEmployee().getName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccine = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        cardRequestPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVaccine.setBackground(new java.awt.Color(97, 212, 195));
        tblVaccine.setForeground(new java.awt.Color(36, 47, 65));
        tblVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Quantity", "Status"
            }
        ));
        tblVaccine.setGridColor(new java.awt.Color(97, 212, 195));
        jScrollPane1.setViewportView(tblVaccine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 420, 180));

        btnRequest.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnRequest.setText("Request Vaccine");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        cardRequestPanel.setBackground(new java.awt.Color(36, 47, 65));
        cardRequestPanel.setMinimumSize(new java.awt.Dimension(670, 848));
        cardRequestPanel.setPreferredSize(new java.awt.Dimension(670, 848));
        cardRequestPanel.setLayout(new java.awt.CardLayout());
        add(cardRequestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PURCHASEWORKAREA.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 100, 850));

        lblText.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 255, 255));
        lblText.setText("Currently Logged in as:");
        add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        lblValue.setFont(new java.awt.Font("Optima", 1, 22)); // NOI18N
        lblValue.setForeground(new java.awt.Color(97, 212, 195));
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        populateTable();
        int count = tblVaccine.getModel().getRowCount();
        System.out.println("Current count -> " + currentCount);
        if(currentCount <= 10){
        ReqVaccineJPanel requestVaccineJPanel = new ReqVaccineJPanel(enterprise.getOrganizationDirectory(), userProcessContainer, organization, enterprise, userAccount);
        cardRequestPanel.add("requestVaccineJPanel", requestVaccineJPanel);
        CardLayout layout = (CardLayout) cardRequestPanel.getLayout();
        layout.next(cardRequestPanel);
        dB4OUtil.storeSystem(system);
        }
        else{
            JOptionPane.showMessageDialog(this, "You already have enough vaccine in stock please utilise them before ordering");
        }

    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequest;
    private javax.swing.JPanel cardRequestPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblVaccine;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblVaccine.getModel();
        model.setRowCount(0);
        UserAccount distributor = new UserAccount();
        try{
        for(WorkReq rv:userAccount.getWorkQueue().getWorkRequestList()){
            System.out.println(enterprise.getName());
//        ArrayList<PurchaseInventory> inv = ((requestVaccine) rv).getInventoryPurchase();
            Object row[] = new Object[4];
            row[0] = rv;
            row[1] = rv.getReceiver().getUsername();
            
//            if(inv!=null){
//            for(PurchaseInventory p : inv){
                
                if(rv.getStatus().equals("Approved")){
                System.out.println(enterprise.getName());
                for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                    for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                        System.out.println(u.getRole().toString());
                        if(u.getRole().toString().equals("Business.Role.DistributionRole")){
                            ((requestVaccine) rv).setDistribution(u);
                            distributor = u;
                            System.out.println(distributor.getUsername());
                            int c = ((requestVaccine) rv).getCount();
                row[2] = c;
                
                currentCount = c;
                ((requestVaccine) rv).setCount(c);
//                            System.out.println(o.getName());
//                            VaccineCount vc = new VaccineCount();
//                            vc.setVaccineName(rv.getReceiver().toString());
//                            vc.setCount(p.getQty());
//                            currEP += p.getQty();
//                            System.out.println(p.getQty());
//                            c+=p.getQty();
//                            System.out.println(c);
                            
//                            DistributionOrganization org = ((DistributionOrganization) o).getVaccineDirectory().add(vc);
                        }
                    }
                }
            }
                
                distributor.getWorkQueue().getWorkRequestList().add(rv);
                
//            }
//            }
            row[3] = rv.getStatus();
            System.out.println(rv.getStatus());
            
//            row[2] = 
            model.addRow(row);
        }
        }
        catch(NullPointerException e){
            System.out.println("No records found");
        }
    }
}
