/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainInterface.SystemAdminPage;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anushkadarade
 */
public class SystemAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminJPanel
     */
    
     JPanel userContainer;
//    EcoSystem ecosystem;
//    UserAccount account;
//    public SystemAdminJPanel(JPanel userProcessContainer,EcoSystem ecosystem)
    public SystemAdminJPanel(JPanel userContainer){
        initComponents();
        this.userContainer= userContainer;
//        this.ecosystem=ecosystem;
//        populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSelectedNode = new javax.swing.JLabel();
        btnMngCustomers = new javax.swing.JButton();
        btnMngManufacturers = new javax.swing.JButton();
        btnMngDeliveryMan = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        lblSelectedNode.setText(" ");

        btnMngCustomers.setText("MANAGE CUSTOMERS");
        btnMngCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCustomersActionPerformed(evt);
            }
        });

        btnMngManufacturers.setText("MANAGE MANUFACTURERS");
        btnMngManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngManufacturersActionPerformed(evt);
            }
        });

        btnMngDeliveryMan.setText("MANAGE DELIVERYMAN");
        btnMngDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngDeliveryManActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(lblSelectedNode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMngManufacturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMngCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMngDeliveryMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSelectedNode)
                .addGap(54, 54, 54)
                .addComponent(btnMngCustomers)
                .addGap(18, 18, 18)
                .addComponent(btnMngManufacturers)
                .addGap(18, 18, 18)
                .addComponent(btnMngDeliveryMan)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCustomersActionPerformed
//        MngCustomerJPanel manageCustomersJPanel = new MngCustomerJPanel(userContainer, account, ecosystem);
        MngCustomerJPanel manageCustomer = new MngCustomerJPanel(userContainer);
        userContainer.add("manageCustomer", manageCustomer);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.next(userContainer);
    }//GEN-LAST:event_btnMngCustomersActionPerformed

    private void btnMngManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngManufacturersActionPerformed
//        ManageRestaurantsJPanel manageRestaurentsJPanel = new ManageRestaurantsJPanel(userProcessContainer, account, ecosystem);
//        userProcessContainer.add("manageRestaurentsJPanel", manageRestaurentsJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngManufacturersActionPerformed

    private void btnMngDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngDeliveryManActionPerformed
//        ManageDeliveryManJPanel managaeDeliveryManJPanel = new ManageDeliveryManJPanel(userProcessContainer, account, ecosystem);
//        userProcessContainer.add("managaeDeliveryManJPanel", managaeDeliveryManJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngDeliveryManActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngCustomers;
    private javax.swing.JButton btnMngDeliveryMan;
    private javax.swing.JButton btnMngManufacturers;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables

    void populateTree() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
