/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainInterface.AdministrativeRole;

import Model.DB4OUtil.DB4OUtil;
import Model.EcoSys;
import Model.Enterprise.Enterprise;
import Model.Organization.Organization;
import Model.Organization.Organization.Type;
import Model.Organization.OrgDirectory;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naisargi Thakkar
 */
public class ManageOrgJPanel extends javax.swing.JPanel {

    private OrgDirectory directory;
    private JPanel userProcessContainer;
    private EcoSys system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private UserAccount account;
    private Enterprise enterprise;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrgJPanel(JPanel userProcessContainer, OrgDirectory directory,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        this.account = account;
        this.enterprise = enterprise;
        //this.enterprise = enterprise;
        
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        cmbOrganization.removeAllItems();
        //System.out.println("User account  --> " + account.getRole().getClass().toString());
        String enterpriseType = enterprise.getClass().toString();
        //System.out.println(enterprise.getClass().toString());
        for (Type type : Type.values()){
            if (enterpriseType.equals("class Model.Enterprise.GovtEnterprise")){
                if(type.equals(Type.Health)){
                   cmbOrganization.addItem(type);
                }
                if(type.equals(Type.Economy)){
                   cmbOrganization.addItem(type);
                }
                if(type.equals(Type.Person)){
                   cmbOrganization.addItem(type);
                }
            } else if(enterpriseType.equals("class Model.Enterprise.HospitalEnterprise")){
                if(type.equals(Type.Doctor)){
                   cmbOrganization.addItem(type);
                }
                if(type.equals(Type.Lab)){
                   cmbOrganization.addItem(type);
                }
                if(type.equals(Type.Pharma)){
                   cmbOrganization.addItem(type);
                }
                
        }
            else if(enterpriseType.equals("class Model.Enterprise.ManufacturerEnterprise")){
                if(type.equals(Type.Manufacturing)){
                   cmbOrganization.addItem(type);
                }
                if(type.equals(Type.Sales)){
                   cmbOrganization.addItem(type);
                }
            } else if(enterpriseType.equals("class Model.Enterprise.DistributorEnterprise")){
                if(type.equals(Type.Purchase)){
                   cmbOrganization.addItem(type);
                }
                if(type.equals(Type.Distribution)){
                   cmbOrganization.addItem(type);
                }
            }
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        cmbOrganization = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(11, 49, 48));
        setMinimumSize(new java.awt.Dimension(1190, 848));
        setPreferredSize(new java.awt.Dimension(1190, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrganization.setBackground(new java.awt.Color(124, 169, 130));
        tblOrganization.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tblOrganization.setForeground(new java.awt.Color(36, 47, 65));
        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrganization.setGridColor(new java.awt.Color(4, 182, 145));
        jScrollPane1.setViewportView(tblOrganization);
        if (tblOrganization.getColumnModel().getColumnCount() > 0) {
            tblOrganization.getColumnModel().getColumn(0).setResizable(false);
            tblOrganization.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 480, 180));

        btnAdd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnAdd.setText("Add Organization");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        cmbOrganization.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 240, -1));

        lblOrganization.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblOrganization.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganization.setText("Organization Type:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ORGANIZATIONS.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        Type type = (Type) cmbOrganization.getSelectedItem();
        System.out.print(type.getValue());
        directory.createOrganization(type);
        System.out.print(type.getValue());
        populateTable();
        System.out.print(type.getValue());
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrganization;
    // End of variables declaration//GEN-END:variables
}
